backend:
  name: git-gateway
  branch: master 

publish_mode: editorial_workflow

media_folder: static/images 
public_folder: /images 

collections:
  - name: posts
    label: Articles
    folder: data/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: json
    fields: 
      - { label: Titre, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: Source, name: src, widget: image }
          - { label: Texte alternatif, name: alt, widget: string }
      - { label: Contenu, name: content, widget: text }